### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by dekimasoon** [kanemototomoki/ts-prisma-graphql#1]
[PlanetGraphQL](https://github.com/planet-graphql/planet-graphql)の作者のdekimasoonと申します。
他に連絡方法が思いつかずIssuesで失礼します。

チュートリアルを進めていただいてありがとうございます！
kanemototomokiさんが初めてだったので嬉しくて連絡してしまいました。
(Githubにpushせずに試してくれた方が他にいらっしゃったかもしれませんが)

もしチュートリアルのどこかでエラーになるとか、進め方の説明が不十分な点があれば、教えていただけると大変ありがたいです！
イシューもすぐクローズしていただいて大丈夫です。突然すみませんでした。ありがとうございました 👍 

---

My name is dekimasoon, author of [PlanetGraphQL](https://github.com/planet-graphql/planet-graphql).
I can't think of any other way to contact you, so please excuse me here.

Thank you for going through the tutorial!
I was so happy to contact you because you are the first person to do so.
(I'm not sure who else might have tried it without pushing it to Github.)

If there are some errors somewhere in the tutorial, or if there are insufficient instructions on how to proceed, I'd be very grateful if you'd let me know!
You can close the issue immediately as well. Sorry for the abruptness. Thank you 👍

**Comment by kanemototomoki** [comment]
@dekimasoon 
初めまして！
素晴らしいチュートリアルをありがとうございます😭
graphQL学習中なのでとても助かっています！
もしチュートリアル中に詰まったことがありましたらzennのdiscussionにて報告させていただきますー！

**Comment by dekimasoon** [comment]
> zennのdiscussionにて報告させていただきますー！

なるほどそれが最高ですね！よろしくお願いいたします！!
突然失礼しました 😅
